spring:
  datasource:
    username: scratchpad
    password: scratchpad
    url: jdbc:postgresql://localhost:5432/scratchpad
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create-drop

app:
  security:
    # base64 encoded secret
    tokenSecret: jf9i4jgu83nfl0adc
  object-storage:
    url: http://172.18.0.2:9000
    buckets:
      logo-name: logo

management:
  server:
    port: 8082
