services:
  postgres:
    # Build image
    image: postgres:my-backend
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    expose:
      - 9000
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
    command: ["minio", "server", "/data", "--console-address", ":9001"]

volumes:
  db-data:
